name: PR Build

on:
  pull_request:
    branches: [ dev ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0       
            
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'

      - run: npm ci --force

      - run: npx prettier --write -l apps

      - run: npx nx affected --target=lint

      - run: npx nx affected --target=stylelint

      - run: npx nx affected --target=build
