version: "3.8"
services:
  db:
    image: postgres
    container_name: saturn-db
    restart: always
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: saturn
    volumes:
      - "/var/lib/postgresql1/data"
    #networks:
    #  - app-network 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: p@ssw0rd
    volumes:
      - "/var/lib/pgadmin"
  app:
    #image: img
    build: ./
    container_name: saturn-app
    depends_on:
      - db
    ports:
      - "44311:44311"